name: faketty
author: Yuri6037
description: FakeTTY GitHub Action (https://github.com/Yuri6037/Action-FakeTTY)
branding:
  icon: 'terminal'
  color: 'white'
runs:
  using: 'node12'
  main: 'index.js'
